"""add_budgeting_system

Revision ID: 16d574376bfd
Revises: 8d60cd58d1ed
Create Date: 2026-05-15 10:40:41.692592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import database.models


# revision identifiers, used by Alembic.
revision: str = '16d574376bfd'
down_revision: Union[str, Sequence[str], None] = '8d60cd58d1ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('amount', database.models.CentsInteger(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.create_index('ix_budgets_lookup', ['company_id', 'category_id', 'year', 'month'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_index('ix_budgets_lookup')

    op.drop_table('budgets')
    # ### end Alembic commands ###
