"""Add account amount snapshots

Revision ID: 58d87d88f841
Revises: 16d574376bfd
Create Date: 2026-06-01 09:18:40.175726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import database.models


# revision identifiers, used by Alembic.
revision: str = '58d87d88f841'
down_revision: Union[str, Sequence[str], None] = '16d574376bfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_amount', database.models.CentsInteger(), nullable=True))
        batch_op.add_column(sa.Column('to_account_amount', database.models.CentsInteger(), nullable=True))
        batch_op.add_column(sa.Column('edv_account_amount', database.models.CentsInteger(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('edv_account_amount')
        batch_op.drop_column('to_account_amount')
        batch_op.drop_column('account_amount')

    # ### end Alembic commands ###
