"""Add period_type to budgets

Revision ID: e8496a85b63b
Revises: 58d87d88f841
Create Date: 2026-06-01 09:33:10.860664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8496a85b63b'
down_revision: Union[str, Sequence[str], None] = '58d87d88f841'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('period_type', sa.String(length=20), server_default='monthly', nullable=False))
        batch_op.alter_column('month',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.alter_column('month',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('period_type')

    # ### end Alembic commands ###
